[build]
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = [
    "--cfg", "wasm_js",
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-Clink-arg=--max-memory=4294967296",
    "-C", "link-arg=--shared-memory",
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--export=__wasm_init_tls",
    "-C", "link-arg=--export=__tls_size",
    "-C", "link-arg=--export=__tls_align",
    "-C", "link-arg=--export=__tls_base",
    "-C", "opt-level=z",
    "-C", "codegen-units=1",
    "-C", "strip=debuginfo",
    "-C", "lto=thin",
    "-C", "embed-bitcode=yes",
]
