[package]
name = "zfun-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
blake2b_simd = "1.0.3"
eyre = "0.6.12"
incrementalmerkletree = "0.8.2"
jubjub = "0.10.0"
group = "0.13.0"
orchard = "0.11.0"
pasta_curves = "0.5.1"
sapling = { package = "sapling-crypto", version = "0.5.0" }
k256 = "0.13.4"
zcash_client_backend = { version = "0.21.0", features = [ "orchard" ] }
zcash_keys = "0.12.0"
zcash_primitives = "0.26.1"
zcash_protocol = "0.7.1"
zcash_script = { version = "0.4.2", default-features = false }
zcash_transparent = "0.6.1"
zip32 = "0.2.1"
uuid = { version = "1.18.1", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.9"
ripemd = "0.1"
hex-literal = "1.0.0"
hex = "0.4.3"
const-str = "0.5"
bincode = "1.3.3"
log = "0.4"

[build-dependencies]
serde_json = "1.0"

[features]
cycle-tracker = []
default = ["cycle-tracker"]

# Enable js feature on getrandom for wasm target
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.16", features = ["js"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_vendor, values("monerochan"))'] }
